import subprocess
import os
import glob

def run_thermal_processing():
    print("--- Step 1: Running Thermal Processor ---")
    try:
        # FIXED: Added "." to tell it to scan the CURRENT folder
        # Added --csv so it actually generates data we might want
        subprocess.run(["python3", "flir_batch_processor.py", ".", "--csv"], check=True)
        print("Thermal processing complete.")
    except subprocess.CalledProcessError as e:
        print(f"Error running thermal processor: {e}")

def generate_index_html():
    print("--- Step 2: Generating Index Page ---")
    
    # Grab all images
    images = glob.glob("*.jpg") + glob.glob("*.png")
    # Filter out non-thermal images if necessary, or just show everything
    images.sort()

    html_content = """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Thermal Imaging Report</title>
        <style>
            body { font-family: sans-serif; padding: 20px; background: #f5f5f5; }
            h1 { color: #333; text-align: center;}
            .gallery { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 20px; padding: 20px; }
            .card { background: white; padding: 15px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); text-align: center; }
            img { max-width: 100%; height: auto; border-radius: 4px; }
            .filename { margin-top: 10px; color: #666; font-size: 0.9em; word-break: break-all; }
        </style>
    </head>
    <body>
        <h1>Thermal Survey Report</h1>
        <p style="text-align:center">Generated by GitHub Actions</p>
        <div class="gallery">
    """

    for img in images:
        html_content += f"""
            <div class="card">
                <a href="{img}"><img src="{img}" alt="{img}"></a>
                <div class="filename">{img}</div>
            </div>
        """

    html_content += """
        </div>
    </body>
    </html>
    """

    with open("index.html", "w") as f:
        f.write(html_content)
    print("index.html successfully created.")

if __name__ == "__main__":
    run_thermal_processing()
    generate_index_html()        <h1>Thermal Processing Results</h1>
        <p>Latest build generated by GitHub Actions.</p>
        <div class="gallery">
    """

    for img in images:
        html_content += f"""
            <div class="card">
                <h3>{img}</h3>
                <a href="{img}"><img src="{img}" alt="{img}"></a>
            </div>
        """

    html_content += """
        </div>
    </body>
    </html>
    """

    with open("index.html", "w") as f:
        f.write(html_content)
    print("index.html successfully created.")

if __name__ == "__main__":
    run_thermal_processing()
    generate_index_html()
