import subprocess
import os
import glob

def run_thermal_processing():
    print("--- Step 1: Running Thermal Processor ---")
    # This runs your existing batch processor
    # ensure flir_batch_processor.py is in the same folder
    try:
        subprocess.run(["python3", "flir_batch_processor.py"], check=True)
        print("Thermal processing complete.")
    except subprocess.CalledProcessError as e:
        print(f"Error running thermal processor: {e}")
        # We don't exit, so we can still try to generate an index of whatever exists

def generate_index_html():
    print("--- Step 2: Generating Index Page ---")
    
    # Find all JPG/PNG images in the current folder (or adjust path if they are in a subfolder)
    images = glob.glob("*.jpg") + glob.glob("*.png")
    images.sort()

    html_content = """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Thermal Imaging Report</title>
        <style>
            body { font-family: sans-serif; padding: 20px; background: #f0f0f0; }
            .gallery { display: flex; flex-wrap: wrap; gap: 10px; }
            .card { background: white; padding: 10px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
            img { max-width: 300px; height: auto; display: block; }
            h1 { color: #333; }
        </style>
    </head>
    <body>
        <h1>Thermal Processing Results</h1>
        <p>Latest build generated by GitHub Actions.</p>
        <div class="gallery">
    """

    for img in images:
        html_content += f"""
            <div class="card">
                <h3>{img}</h3>
                <a href="{img}"><img src="{img}" alt="{img}"></a>
            </div>
        """

    html_content += """
        </div>
    </body>
    </html>
    """

    with open("index.html", "w") as f:
        f.write(html_content)
    print("index.html successfully created.")

if __name__ == "__main__":
    run_thermal_processing()
    generate_index_html()
