import fs from "fs";
import path from "path";

export interface AppSettings {
  // Google Drive integration
  driveSourceFolderId: string;
  driveSourceFolderName: string;
  driveOutputFolderId: string;
  driveOutputFolderName: string;
  autoSaveToDrive: boolean;

  // Survey defaults
  defaultSensitivity: number;
  defaultInspectorName: string;
  organisationName: string;

  // Report branding
  reportHeaderText: string;
  reportFooterText: string;
}

const SETTINGS_PATH = path.join(process.cwd(), "settings.json");

const DEFAULT_SETTINGS: AppSettings = {
  driveSourceFolderId: "",
  driveSourceFolderName: "",
  driveOutputFolderId: "",
  driveOutputFolderName: "",
  autoSaveToDrive: false,
  defaultSensitivity: 2.0,
  defaultInspectorName: "",
  organisationName: "",
  reportHeaderText: "Thermal Survey Report",
  reportFooterText: "Generated by Thermal Survey Reporter",
};

export function loadSettings(): AppSettings {
  try {
    if (fs.existsSync(SETTINGS_PATH)) {
      const raw = fs.readFileSync(SETTINGS_PATH, "utf-8");
      const parsed = JSON.parse(raw);
      return { ...DEFAULT_SETTINGS, ...parsed };
    }
  } catch (e) {
    console.error("Failed to load settings:", e);
  }
  return { ...DEFAULT_SETTINGS };
}

export function saveSettings(settings: Partial<AppSettings>): AppSettings {
  const current = loadSettings();
  const updated = { ...current, ...settings };
  fs.writeFileSync(SETTINGS_PATH, JSON.stringify(updated, null, 2), "utf-8");
  return updated;
}
