name: Process Thermal Images

on:
  push:
    branches: ["main"]
  workflow_dispatch: # Allows you to click a button to run it manually

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Perl (for ExifTool)
        run: sudo apt-get update && sudo apt-get install -y libimage-exiftool-perl

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Processing & Build Site
        run: |
          # If you have extra python libraries, install them here:
          # pip install pillow 
          
          python3 build_site.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
